### PR TITLE
Improve blog posts

### PR DESCRIPTION
**Pull request by desilinguist**
- Show "Read more..." after each blog post.
- Add a more descriptive excerpt for the first post.
- Add in Regina's avatar (basically @callison-burch's change from his mistargeted PR).

### CODE REVIEW

**Comment by knmnyn** [comment]
990301-cochairs

This image needs to go into the images/ subdir but has gone missing from the original PR...

**Comment by knmnyn** [comment]
Hi all:

When can this pull request go live?  I'm not sure whether you are waiting on our (PC chairs') side.  Please elaborate if yes...

**Comment by desilinguist** [comment]
@knmnyn I am waiting for Regina to actually tell us whether she wants to continue using the blog in this website or set up something else. You are on those emails as well where she said she is exploring alternatives since she does not like the current design/formatting of this website.

In general, a PR can only be merged if all assigned reviewers approve it. @callison-burch hasn't approved this yet.

**Comment by knmnyn** [comment]
Oh, I see.  I will talk with her then.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by callison-burch** [comment]
lgtm (looks good to me)

**Comment by desilinguist** [comment]
This is no longer useful since the blog will be moved elsewhere. I will submit another PR removing the blog post.

**Pull request closed without merging**
