### PR TITLE
Add page listing workshops and links.

### PR DESCRIPTION
**Pull request by desilinguist**
- Added a tab for "Workshops" to the masthead navigation.
- Added a placeholder page under "Calls -> Workshops" that links to the list of workshop page.
- Added a notice to home page that links to the list of workshop page.

### CODE REVIEW

**Comment by callison-burch** [comment]
Looks fine to me.  The workshops don't seem to be in any particular order.  Maybe sort them alphabetically?  Or once it is known, split them into which day(s) they will be held on.

**Comment by desilinguist** [comment]
Good point. Given that we don't even have websites for two of the workshops, I think I will just sort them alphabetically for now and then update the page when the dates are known.

**Comment by desilinguist** [comment]
@callison-burch can you explicitly approve the PR? It's a new thing that GitHub added and once you assign reviewers, you need them to approve to merge :)

**Comment by callison-burch** [comment]
Sure - How do I do that?

**Comment by desilinguist** [comment]
You should see a button to approve when you look at the changes in the PR

**Comment by desilinguist** [comment]
I am going to merge this now since I think we really need to put up this list. The only workshop that doesn't have a URL is BUCC but they still haven't responded to Wei's emails. They'll just have to get the URL to me later and I can make a separate PR to update that date.

@aestuary can you please publicize that we have now posted the list of workshops?

**Comment by knmnyn** [comment]
Good point.  Thanks for putting this up right away!


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Pull request merged**
