### PR TITLE
First blog post

### PR DESCRIPTION
**Pull request by knmnyn**
Hi all:

I've created the first blog post.  Added the appropriate image and field tested in on my install.  Please proofcheck!

### CODE REVIEW

**Comment by callison-burch** [comment]
I merged this.  I think that it would be good for the Recent Posts section to have a "Read more" link.  I'll ask Nitin to add it.

**Comment by desilinguist** [comment]
I was in the middle of reviewing this and had found some errors. I think
t'd be a good idea to wait for all the reviewers to approve the PR before
merging.

**Comment by callison-burch** [comment]
Sounds good.  How do I tell if there are multiple reviewers?

**Comment by desilinguist** [comment]
The author of the PR should assign reviewers. I had done that for this PR since Min-Yen didn't do it this time. I think the best process is for all assigned reviewers to simply add their review saying things look good and then I can merge it once all the reviews are in.

**Comment by desilinguist** [comment]
I am going to revert this PR for now.

**Comment by desilinguist** [comment]
@knmnyn can you please re-submit your PR? Sorry about the mix-up. I should have sent clearer instructions.

**Comment by callison-burch** [comment]
Sounds good to me.

**Comment by knmnyn** [comment]
Ok.  Sorry, I forgot to do this!

**Pull request merged**
