### PR TITLE
Avatar for regina

### PR DESCRIPTION
**Pull request by callison-burch**

### CODE REVIEW

**Comment by desilinguist** [comment]
@callison-burch you have the wrong base branch. You want to merge into `master` not `enable-blog`.

**Comment by callison-burch** [comment]
Hmm, any idea on how I change the target after I have made a PR?

**Comment by desilinguist** [comment]
Unfortunately, I don't think Github allows that. I am going to close this PR and you will have to resubmit it.

**Comment by callison-burch** [comment]
OK

**Pull request closed without merging**
