### PR TITLE
Add information about registration, accommodation, and social event

### PR DESCRIPTION
**Pull request by desilinguist**
- Add new masthead link for "Registration" and new page with registration information.
- Add new masthead link for "Participants" (a la ACL 2016) which points to the pages for hotel accommodations and the social event.
- Move the calls for papers and demos to an archive page and link that page to the "Archive" link in the masthead.
- Create student reservation request form in Google Forms and link it to the accommodation page. The Google Form is shared with Priscilla.
- Add news items about registration, accommodation, and social event to the home page.

### CODE REVIEW

**Comment by callison-burch** [comment]
I also recommend removing the "Official website." links for the hotels, since it may confuse people who are trying to book the conference rate.

**Comment by desilinguist** [comment]
@callison-burch the only reason I have them there is sometimes people might want to actually visit the official website to see what the hotel is like and the reservation links do not always point to the official website.

**Comment by desilinguist** [comment]
Also, if I add "Social Event" as its own category in the masthead, the links don't fit in the desktop version of the website which I don't like. Any suggestions as to where to move "Social Event"?

**Comment by callison-burch** [comment]
I think that we shouldn't include the social event in the masthead.  I recommend just leaving it off for now, and when we have the day-by-day program ready, we can include it there.

**Comment by desilinguist** [comment]
Hi @callison-burch, I incorporated your suggestions. If you get a chance, take a look. I will merge EOD. Thanks!

**Comment by callison-burch** [comment]
Minor suggestion: move the Accommodation tab to be adjacent to the Registration tab in the masthead.

**Comment by callison-burch** [comment]
Another suggestion about the Social Event details.  You could create a separate page for it and link to it from the "What’s included" section of the Registration page.  The social event is described in the second paragraph of that section.

**Comment by desilinguist** [comment]
That's perfect, @callison-burch! Done :)

**Comment by callison-burch** [comment]
For the news alert: could you change "Please register and book your rooms at the discounted rates as soon as possible" to "Please book your rooms at the discounted rates as soon as possible.  There are several other large events being held in Vancouver at the same time as ACL, and we expect the hotels to fill up."

**Pull request merged**
